# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170515_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='\u63a5\u53d7\u7528\u6237ID'),
        ),
    ]
